/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bessy_hzb_application_machine_NativeBridgeWithCPP */

#ifndef _Included_bessy_hzb_application_machine_NativeBridgeWithCPP
#define _Included_bessy_hzb_application_machine_NativeBridgeWithCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bessy_hzb_application_machine_NativeBridgeWithCPP
 * Method:    sayHello
 * Signature: ([DLjava/lang/String;Ljava/lang/String;D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_bessy_hzb_application_machine_NativeBridgeWithCPP_sayHello
  (JNIEnv *, jobject, jdoubleArray, jstring, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
